# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2536a7e344623881217ef24140b3c5039ac475c6b7a1efb4baab11115ff07c2754d3181ada79814f4eb6eb38702920f9bee841b2b2715c205a8d04c53fe35b0

test:
  secret_key_base: 997cb6f682969b5ac3e9c2bbdebb0f5df4432b23497a5c533ebbb99c3fa814636b59b7d09744d60d17b19951081bf3cc2dfa3ed5cdd919269d8ad29b8f70131f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
